source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

target 'CognitoYourUserPoolsSample' do
    pod 'AWSCore'
    pod 'AWSCognitoIdentityProvider'
    pod 'AWSAPIGateway'
    pod 'AWSLambda'
    pod 'AWSDynamoDB'
    pod 'AWSCognito'
end
